# Site settings
title: 'ricefield' # Your Title
tagline: 'Notes on culture, technology, God, and the bible' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: "" # the subpath of your site, e.g. /blog/
